name: PlatformIO Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create placeholder secrets.cpp if missing
        run: |
          if [ ! -f src/secrets.cpp ]; then
            mkdir -p src
            echo "I2luY2x1ZGUgXCJzZWNyZXRzLmhcIi8KLy8gUGxhY2Vob2xkZXIgdmlhbHVlcyB1c2VkIG9ubHkgZm9yIFJJQy5jIiAgICAgIA==" | base64 -d > src/secrets.cpp
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio

      - name: Build firmware (PlatformIO)
        run: pio run -e esp32dev

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: firmware-artifacts
          path: .pio/build
