name: PlatformIO Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build (PlatformIO)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio

    - name: Run PlatformIO build
      run: |
        pio run -e esp32dev --silent

    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: firmware-artifacts
        path: .pio/build
