name: PlatformIO Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build (PlatformIO)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Provide placeholder secrets for CI (no real secrets committed)
      run: |
        if [ ! -f src/secrets.cpp ]; then
          echo "Creating temporary src/secrets.cpp for CI build"
          mkdir -p src
          cat > src/secrets.cpp <<'EOF'
#include "secrets.h"

// Placeholder values used only for CI. Replace with real secrets locally.
const char* WIFI_SSID = "";
const char* WIFI_PASS = "";

const char* MQTT_SERVER = "broker.hivemq.com";
int MQTT_PORT = 1883;
const char* MQTT_TOPIC = "esp32/sensors/uhi";

const bool ENABLE_DEEP_SLEEP = false;
const unsigned long DEEP_SLEEP_SECONDS = 60;
EOF
        else
          echo "src/secrets.cpp already present"
        fi

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio

    - name: Run PlatformIO build
      run: |
        pio run -e esp32dev --silent

    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: firmware-artifacts
        path: .pio/build
